# Generated by Django 4.0.3 on 2022-04-30 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(default='Y0lZBF_DwiE', unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='IngredientsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(verbose_name='quantity')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.ingredient', verbose_name='ingredient')),
            ],
            options={
                'verbose_name': 'ingredients list',
                'verbose_name_plural': 'ingredients lists',
            },
        ),
        migrations.CreateModel(
            name='Kitchenware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
            ],
            options={
                'verbose_name': 'kitchenware',
                'verbose_name_plural': 'kitchenwares',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('symbol', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(default='2y0wcSC0duY', unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('instructions', models.TextField(default='#Brak instrukcji', help_text='Steps separator is semi-colon', verbose_name='instructions')),
                ('ingredients', models.ManyToManyField(through='blog.IngredientsList', to='blog.ingredient', verbose_name='ingredients')),
                ('kitchenware', models.ManyToManyField(to='blog.kitchenware', verbose_name='Kitchenware')),
            ],
            options={
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('meals', models.ManyToManyField(related_name='recipe', to='blog.recipe', verbose_name='meals')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
            },
        ),
        migrations.AddField(
            model_name='ingredientslist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.recipe', verbose_name='recipe'),
        ),
        migrations.AddField(
            model_name='ingredientslist',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='blog.unit'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('publish_date', models.DateTimeField(verbose_name='publish date')),
                ('short_content', models.TextField(verbose_name='short content')),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
